version: "3.8"

services:
  backend:
    build:
      context: ./Backend
    ports:
      - "4000:4000"
    volumes:
      - ./Backend:/app
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_BASE_API=http://backend:4000/api

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: blooogy
    ports:
      - "8000:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
